src/PwebBundle/Entity/Bilan.php
<?php

namespace PwebBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Bilan
 *
 * @ORM\Table(name="bilan")
 * @ORM\Entity(repositoryClass="PwebBundle\Repository\BilanRepository")
 */
class Bilan
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    
	
	/**
	 * @ORM\OneToOne(targetEntity="PwebBundle\Entity\Session", inversedBy="bilan")
	 * @ORM\JoinColumn(onDelete="CASCADE")
	 */
	private $session;
    
    /**
	 * @ORM\OneToMany(targetEntity="PwebBundle\Entity\Resultat",cascade = {"persist","remove"}, mappedBy="bilan")
	 */
	private $resultats;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set note
     *
     * @param float $note
     *
     * @return Bilan
     */

    /**
     * Set session
     *
     * @param \PwebBundle\Entity\Session $session
     *
     * @return Bilan
     */
    public function setSession(\PwebBundle\Entity\Session $session)
    {
        $this->session = $session;
        return $this;
    }

    /**
     * Get session
     *
     * @return \PwebBundle\Entity\Session
     */
    public function getSession()
    {
        return $this->session;
    }
	
	public function calculerNote()
    {	
		//On laisse cette fonction ici pour éviter tout bug d'appel sur cette fonction.
		return ;
	}
    
    public function getNombreParticipants(){
        $eleves = 0;
        foreach($this->session->getGroupes() as $grp){
            foreach ($grp->getEleves() as $eleve){
                if ($eleve->hasParticipated($this->session)){
                    $eleves++;
                }
            }
        }
        
        return $eleves;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->resultats = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add resultat
     *
     * @param \PwebBundle\Entity\Resultat $resultat
     *
     * @return Bilan
     */
    public function addResultat(\PwebBundle\Entity\Resultat $resultat)
    {
        if (!inArray ($resultat , $this->resultats)){
            $this->resultats[] = $resultat;
            $resultat->setBilan($this);
        }
        return $this;
    }

    /**
     * Remove resultat
     *
     * @param \PwebBundle\Entity\Resultat $resultat
     */
    public function removeResultat(\PwebBundle\Entity\Resultat $resultat)
    {
        $this->resultats->removeElement($resultat);
        $resultat->setBilan(null);
    }

    /**
     * Get resultats
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getResultats()
    {
        return $this->resultats;
    }
}

src/PwebBundle/Resources/views/Menu/QCM.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block pweb_body %}
    <h2>Gestion des QCM</h2>
    
<div id="qcm_select_box">
    
    <a class="navigation"href="{{ path('pweb_QCM_create') }}" > Créer un nouveau QCM </a>

    {% for qcm in listeQCM %}
        <div class="qcm">
            <h2>{{ qcm.theme }}</h2>
			<div class="questions">
			{% for question in qcm.questions %}

				<div >
					<h3>{{ question.titre }}</h3>
					<p> {{ question.text }} </p>
				</div>

			{% endfor %}
		</div>
            <div class="mini_nav_box">
                 <a class="mini_navigation" href="{{ path('pweb_question_add', {'id' : qcm.id }) }}" > Ajouter une question</a>
                 <a class="mini_navigation" href="{{ path('pweb_QCM_delete', {'id' : qcm.id }) }}" > Supprimer</a>
                 <a class="mini_navigation" href="{{ path('pweb_QCM_edit', {'id' : qcm.id }) }}" > Editer</a>
                 <a class="mini_navigation" href="{{ path('pweb_session_create', {'id' : qcm.id }) }}" > Lancer session de test</a>
            </div>

        </div>
    {% endfor %}
</div>
{% endblock %}

src/PwebBundle/Resources/views/Menu/editProfil.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Profil - {{ parent() }}
{% endblock %}

{% block pweb_body %}
    
    <h2>Editer profil</h2>
    <div id="profil_edit_box">
    <div> {{ form(form) }} </div>
    </div>
    
{% endblock %}

src/PwebBundle/Resources/views/Menu/index.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block pweb_body %}

    <h2>Menu principal</h2>

    <div id="nav_box">
        <a class="navigation" href="{{path ('pweb_QCM_select')}}">QCM</a>
        <a class="navigation" href="{{path ('pweb_profil')}}">Profil</a>
        <a class="navigation" href="{{path ('pweb_results')}}">Resultats</a>
    </div>
    
{% endblock %}

src/PwebBundle/Resources/views/Menu/newQCM.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  QCM - {{ parent() }}
{% endblock %}

{% block pweb_body %}
	<h2>{{ action }} d'un QCM</h2>
    <div id="profil_edit_box">
    <div> {{ form(form) }} </div>
    </div>
    
{% endblock %}

src/PwebBundle/Resources/views/Menu/newQuestion.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Question - {{ parent() }}
{% endblock %}

{% block pweb_body %}

    <h2 style="padding-bottom: 50px;">Création d'une question</h2>
    <div id="profil_edit_box">
		<div>
			{{ form_start(form) }}

			{{ form_errors(form) }}

			<div>
				{{ form_label(form.titre, "Titre de la question :") }}
				{{ form_row(form.titre) }}
				{{ form_errors(form.titre) }}
			</div>
			
			<div>
				{{ form_label(form.text, "Contenu") }}
				{{ form_row(form.text) }}
				{{ form_errors(form.text) }}
			</div>
			{{ form_rest(form) }}
			{{ form_row(form.reponses) }}
			<a href="#" id="add_reponse">Ajouter une réponse</a>
			{{ form_widget(form.save) }}
			{{ form_end(form) }}
			
		</div>
	</div>
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
    
            var $container = $('div#pwebbundle_question_reponses');


            var index = $container.find(':input').length;

        $('#add_reponse').click(function(e) {
            addReponse($container);

            e.preventDefault(); // évite qu'un # apparaisse dans l'URL
            return false;
        });

    
        if (index == 0) {
            addReponse($container);
        } 
        else
        {
            $container.children('div').each(function() {
                addDeleteLink($(this));
            });
        }

    // La fonction qui ajoute un formulaire ReponseType
            function addReponse($container) {
              // Dans le contenu de l'attribut « data-prototype », on remplace :
              // - le texte "__name__label__" qu'il contient par le label du champ
              // - le texte "__name__" qu'il contient par le numéro du champ
                var template = $container.attr('data-prototype')
                    .replace(/__name__label__/g, 'Reponse ' + (index+1))
                    .replace(/__name__/g,        index)
                ;

                var $prototype = $(template);

                addDeleteLink($prototype);

                $container.append($prototype);

                index++;
            }

    // La fonction qui ajoute un lien de suppression d'une catégorie
            function addDeleteLink($prototype) {
                var $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');
                $prototype.append($deleteLink);
                $deleteLink.click(function(e) {
                    $prototype.remove();
                    e.preventDefault();
                    return false;
                });
            }
        });
    </script>
    
{% endblock %}

src/PwebBundle/Resources/views/Menu/newSession.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block pweb_body %}

    <h2>Lancer nouvelle session</h2>
    
    <div> {{ form(form) }} </div>
    
{% endblock %}

src/PwebBundle/Resources/views/Menu/profil.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block pweb_body %}

    <h2> Profil </h2>
    <div id="profil_box">
        {% if app.user.image is not null %}
        <img src="{{ asset(app.user.image.WebPath)  }}" alt="photo de profil" height="300" width="300">
        <div id="trait"></div>
        {% endif %}
        <div>
            <h3> {{ app.user.nom }}  {{ app.user.prenom }} </h3>
            <p>    {% if app.user.groupe is not null %}
                    groupe {{ app.user.groupe.valeur }} en {{ app.user.groupe.promotion.valeur }}  
                {% endif %}
            </p>
            <p> email : {{ app.user.email }} </p>

            <a class="navigation" href="{{path ('pweb_profil_edit')}}"><div>Editer profil</div></a>
        </div>
    </div>

{% endblock %}

src/PwebBundle/Resources/views/Menu/results.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Resultats - {{ parent() }}
{% endblock %}

{% block pweb_body %}
    <div id="session_nav_box" >
        {% for session in sessions %}
        <div>
            <h2> {{ session.titre }} le {{ session.date|date("m/d/Y", "Europe/Paris") }}</h2>
            <h3> Theme : {{ session.QCM.theme }}</h3>
            <p> Avec {{ session.prof.prenom }} {{ session.prof.nom }}</p>
            <a class="navigation" href="{{ path('pweb_session', {'id' : session.id}) }}">Consulter</a>
        </div>
        {% endfor %}
    </div>

{% endblock %}

src/PwebBundle/Resources/views/Menu/session.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Session de test - {{ parent() }}
{% endblock %}

{% block meta %}<meta http-equiv="refresh" content="5">{% endblock %}

{% block pweb_body %}

    <div id="session_box">
    <h2> Session {{ session.titre }}</h2>
    
    <ol type="I">
        {% for question in session.questions %}
            <li>    <h3> {{ question.text }} </h3>
                
                    {% for reponse in question.reponses %}
							<p>{{ reponse.text }}</p>
                            {% if session.active %}
                                
                                {% set found = '' %}
                                {% for resultat in app.user.resultats %}
                                    {% if resultat.reponse == reponse %}
                                        {% set found = 'true' %}
                                    {% endif %}
                                {% endfor %}
                            
                            
                                {% if found == 'true' %}
                                    <a class="navigation" href="{{ path('pweb_result_remove', {'sessionId' : session.id , 'reponseId' : reponse.id}) }}">Retirer réponse</a>
                                {% else %}
                                    <a class="navigation" href="{{ path('pweb_result_add', {'sessionId' : session.id , 'reponseId' : reponse.id}) }}">Ajouter réponse</a>
                                {% endif %}
                            {% else %}
                               
                            {% endif %}
                        
                    {% endfor %}
                
            </li>
        {% endfor %}
    </ol>
    
    <div id="bilan_retour_box">{{ include ('PwebBundle:Include:bilanRetour.html.twig') }}</div>
    </div>

{% endblock %}

src/PwebBundle/Resources/views/Menu/sessionManagement.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Session - Prof - {{ parent() }}
{% endblock %}


{% block pweb_body %}

    <h2> Session {{ session.titre }}</h2>
    <div id="session_manag_box">
        {% if session.showResults %}
            <a class="navigation" href="{{path('pweb_session_showResults', { 'id' : session.id}) }}">Masquer résultats</a>
        {% else %}
            <a class="navigation" href="{{path('pweb_session_showResults', { 'id' : session.id}) }}">Afficher résultats</a>
        {% endif %}
        
        
        {% for question in session.QCM.questions %}
            <div class="intern">
                <div>
                    <h3> {{ question.titre }} </h3>
                    <p> {{ question.text }} </p>
                </div>
                <div>
                {% if question in session.questions %}
                    {% if session.showResults %}
                        {%  for reponse in question.reponses %}
                            {{ render(controller('PwebBundle:Pweb:resultCount' , {'bilan' : session.bilan , 'reponse' : reponse})) }} 
                        {% endfor %}
                    {% endif %}
                {% elseif session.active %}
                    <a class="navigation"href="{{ path('pweb_session_question_add' , { 'sessionId' : session.id , 'questionId' : question.id} ) }}">Ajouter question à la session</a>
                {% endif %}
                </div>
            </div>
        {% endfor %}
        {% if session.active %}
            <a class="navigation" href="{{ path('pweb_session_end' , { 'id' : session.id}) }}"> Fin de session </a>
        {% else %}
    
        {{ include ('PwebBundle:Include:bilanRetour.html.twig') }}
		{% endif %}
    </div>

{% endblock %}

src/PwebBundle/Resources/views/Menu/session_bilan.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Bilan - {{ parent() }}
{% endblock %}

{% block pweb_body %}


	<h2>Bilan de session : {{ session.titre }}</h2>
	<div class="session_bilan_box">
		{% for eleve in eleves %}
			{% if eleve.hasParticipated(session) %}
			<div class="eleve_result">
				{% if eleve.image is not null %} <img src="{{ asset (eleve.image.WebPath) }}" alt="Photo de profil" height="80" width="80"> {% endif %}
				<p>{{eleve.nom}} {{eleve.prenom}} à obtenu la note de <strong style="color:blue;">{{resultat.note(session, eleve) | number_format(2,',','')}} / 20 </strong>.</p>
			</div>
			{% endif %}
		{% endfor %}
		
		<p> La moyenne pour cette session est de  <strong style="color:blue;">{{ resultat.getMoyenne(session)| number_format(2,',','') }} / 20</strong> avec {{ session.bilan.nombreParticipants}} participants.</p>
		<p> La meilleure note est de  <strong style="color:green;">{{ resultat.PlusHaute(session)| number_format(2,',','') }} / 20</strong>.</p>
		<p> La pire note est de  <strong style="color:red;">{{ resultat.PlusBasse(session) | number_format(2,',','')}} / 20</strong>.</p>
		<ol type="I">
			{% for question in session.questions %}
				<li>    <h3> {{ question.text }} </h3>
					<ol type="a">
						{% for reponse in question.reponses %}
							<li>
								<div {% if reponse.estValide %}
								class="bonne"
								{% else %}
								class="mauvaise"
								{% endif %} >{{ render(controller('PwebBundle:Pweb:resultCount' , {'bilan' : session.bilan , 'reponse' : reponse})) }}</div>
								
							</li>
							<p><br\></p>
						{% endfor %}
					</ol>
				</li>
			{% endfor %}
			<div id="centered"><a class="navigation" href="{{ export.exporter(session) }}" >Exporter</a></div>
		</ol>
	</div>
        
{% endblock %}

src/PwebBundle/Resources/views/Menu/session_bilan_etu.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block pweb_body %}
    
    <h2> Session {{ session.titre }}</h2>
    <div class="session_bilan_box">
		<ol type="I">
			{% for question in session.questions %}
				<li>    <h3> {{ question.text }} </h3>
					<ol type="a">
						{% for reponse in question.reponses %}
							<li>
								<div style="padding-top:10px;" {% if reponse.estValide %}
								class="bonne"
								{% else %}
								class="mauvaise"
								{% endif %} ><p><strong>{{ reponse.text }} </strong></p></div>
								{% set found = '' %}
								{% for resultat in app.user.resultats %}
									{% if resultat.reponse == reponse and resultat.bilan.session == session %}
										{% set found = 'true' %}
									{% endif %}
								{% endfor %}
									
								{% if found == 'true' %}
									{% if reponse.estValide %}
										<p>Vous avez eu la bonne réponse.</p>
									{% else %}
										<p>Vous vous êtes trompé.</p>
									{% endif%}
								{% elseif reponse.estValide %}
									<p>Il vous manquait cette réponse.</p>
								{% endif %}
								
							</li>
						{% endfor %}
					</ol>
				</li>
			{% endfor %}
			<p> <br> Votre note <strong style="color:blue;">{{ resultat.getNote(session, app.user) | number_format(2,',','')}} / 20 </strong> </p>
			<p> La moyenne de la classe est de <strong style="color:blue;">{{  resultat.getMoyenne(session) | number_format(2,',','') }} / 20</strong> avec {{ session.bilan.nombreParticipants}} participants.</p>
			
		</ol>
    </div>
    
{% endblock %}

src/PwebBundle/Resources/views/Menu/session_select.html.twig
{% extends "PwebBundle::layout.html.twig" %}

{% block title %}
  Selection session - {{ parent() }}
{% endblock %}

{% block pweb_body %}

    <h2>Selection de session</h2>
    
    {% if sessions is empty %}
    <p style="text-align:center;">Il n'y a pas de session active pour le moment.</p>
    <a class="navigation" href="{{ path('pweb_homepage') }}">Retour</a>
    {% else %}
    
    <div id="session_nav_box" >
        {% for session in sessions %}
        <div>
            <h2> {{ session.titre }} le {{ session.date|date("m/d/Y", "Europe/Paris") }}</h2>
            <h3> Theme : {{ session.QCM.theme }}</h3>
            <p> Avec {{ session.prof.prenom }} {{ session.prof.nom }}</p>
            <a class="navigation" href="{{ path('pweb_session', {'id' : session.id}) }}">Participer</a>
        </div>
        {% endfor %}
    </div>
    
    {% endif %}

{% endblock %}